#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "molokai"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    max_column = 80
    enable_statusline_display_mode = false
    default_indent = 4
    expand_tab = 1
    relativenumber = 0
    lint_on_the_fly = 1
    lint_on_save = 1

    bootstrap_after = "myspacevim#after"


[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#xml'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#javascript'
  
[[layers]]
  name = 'VersionControl'

[[custom_plugins]]
  name = 'python-mode/python-mode'

[[custom_plugins]]
  name = 'google/vim-searchindex'
